# -*- coding: utf-8 -*-
"""Task12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rQMOEbwm5OmHbO9paeHpZiy9pfgNqC0W
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_excel("/content/Titanic-Dataset.xlsx")

print("Dataset loaded successfully!")

df.shape

df.info()

df.head(10)

print(df.dtypes)

# Check the missing values

df.isnull().sum()

"""Embarked column having 2 null values. Fill with Mode because Only 2 values are missing. Filling with the most frequent port (S) preserves the rows without distorting the data."""

print(df["Embarked"].value_counts())

print("Missing Embarked values:", df["Embarked"].isnull().sum())

Missing_Values = df['Embarked'].mode()[0]
df['Embarked'] = df['Embarked'].fillna(Missing_Values)

df.info()

"""Age column having null values 177. Fill with Median Age is numeric and skewed. The median is safer than the mean because it isn't pulled by outliers."""

print("Missing Age values:", df["Age"].isnull().sum())

"""Contained 177 missing values (~19.9%). To preserve the sample size without introducing outlier distortions, these records were imputed using the median age of the dataset"""

median_age = df['Age'].median()
df['Age'] = df['Age'].fillna(median_age)

df.info()

"""Cabin column having 687 null values. Drop or Mark 'Unknown'Over 77% of the column is missing. Imputing it accurately is impossible, so we explicitly label the missing data as 'Unknown'.
if it is not necessary then delete column from dataset.
"""

df['Cabin'] = df['Cabin'].fillna('Unknown')

"""Cabin column Had the highest amount of missing data with 687 missing values (~77.1%). Because over three-quarters of the data was missing, filling this with a calculated metric was unfeasible. The missing gaps were explicitly categorized as 'Unknown'"""

print(df.isnull().sum())

"""This the graphs which shows missing values"""

# 1. Prepare the missing data
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

# 1. RELOAD THE ORIGINAL DATA SO WE CAN VISUALIZE THE GAPS
# Change this path to match how you originally loaded your file (e.g., pd.read_excel or pd.read_csv)
df_original = pd.read_excel("/content/Titanic-Dataset.xlsx")

# 2. Calculate missing values using the original data
missing_counts = df_original.isnull().sum()
missing_pct = (df_original.isnull().sum() / len(df_original)) * 100

# Filter only columns that have missing data
missing_data = missing_counts[missing_counts > 0].sort_values(ascending=True)
missing_pct = missing_pct[missing_data.index]

# 3. Plotting
if not missing_data.empty:
    plt.figure(figsize=(10, 5))
    colors = sns.color_palette("muted", len(missing_data))
    bars = plt.barh(missing_data.index, missing_data.values, color=colors, edgecolor='black')

    # Add data labels (Counts and Percentages)
    for bar, pct in zip(bars, missing_pct):
        width = bar.get_width()
        plt.text(width + 10, bar.get_y() + bar.get_height()/2,
                 f'{int(width)} ({pct:.1f}%)',
                 va='center', ha='left', fontweight='bold', fontsize=10)

    # Styling
    plt.title("Missing Value Analysis - Titanic Dataset", fontsize=14, fontweight='bold', pad=15)
    plt.xlabel("Number of Missing Records", fontsize=12)
    plt.ylabel("Features / Columns", fontsize=12)
    plt.xlim(0, max(missing_data.values) + 100)
    sns.despine()
    plt.tight_layout()
    plt.show()
else:
    print("All missing values have already been handled! No gaps to plot.")

